Added the ability to use CORS for all sources
harshavardhana/s3www pull request #27
Opened 2023-09-20 12:15 UTC by ilyajob05

Enabled the ability to use CORS for all sources 
Cross-Origin Resource Sharing ([CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS))

2023-09-20 12:24 UTC, ilyajob05 commented
Hi all!
I added the ability to include braids in the header; to do this, just add a flag **-lets-CORS** to the arguments  and checked the functionality

```
./s3www -endpoint "https://s3-aws.com" -accessKey "KEY" -secretKey "KEY" -bucket "bucket" -address "0.0.0.0:80" -lets-CORS
```

2023-09-20 15:20 UTC, harshavardhana requested changes
If you want to enable cors add rs/cors dependency and use that handler instead.

2023-09-21 07:32 UTC, harshavardhana requested changes

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +	var mux_handler http.Handler
```suggestion
	var muxHandler http.Handler
```

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +		mux_handler = cors.Default().Handler(mux)
```suggestion
		muxHandler = cors.Default().Handler(mux)
```

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +		mux_handler = mux
```suggestion
		muxHandler = mux
```

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +		certmagic.HTTPS([]string{address}, mux_handler)
```suggestion
		certmagic.HTTPS([]string{address}, muxHandler)
```

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +		log.Fatalln(http.ListenAndServeTLS(address, tlsCert, tlsKey, mux_handler))
```suggestion
		log.Fatalln(http.ListenAndServeTLS(address, tlsCert, tlsKey, muxHandler))
```

2023-09-21 07:32 UTC, harshavardhana commented on main.go
> +		log.Fatalln(http.ListenAndServe(address, mux_handler))
```suggestion
		log.Fatalln(http.ListenAndServe(address, muxHandler))
```

2023-09-21 07:36 UTC, harshavardhana requested changes
You can also add 

```
        opts := cors.Options{
                AllowOriginFunc: func(origin string) bool {
                        for _, allowedOrigin := range allowedOrigins {
                                if wildcard.MatchSimple(allowedOrigin, origin) {
                                        return true
                                }
                        }
                        return false
                },
                AllowedMethods: []string{
                        http.MethodGet,
                        http.MethodPut,
                        http.MethodHead,
                        http.MethodPost,
                        http.MethodDelete,
                        http.MethodOptions,
                        http.MethodPatch,
                },
                AllowedHeaders:   []string{"*"},
                ExposedHeaders:   []string{"*"},
                AllowCredentials: true,
        }
        return cors.New(opts).Handler(handler)
```

2023-09-21 07:36 UTC, harshavardhana commented on main.go
> +        flag.BoolVar(&letsCORS, "lets-CORS", defaultEnvBool("S3WWW_LETS_CORS", false), "enable Let's CORS for Cross-Origin Resource Sharing")
```suggestion
```

No need for this flag, enable CORS by default

2023-09-21 07:36 UTC, harshavardhana commented on main.go
> +	if letsCORS {
Enable this by default.

2023-09-22 16:30 UTC, harshavardhana requested changes

2023-09-22 16:30 UTC, harshavardhana commented on main.go
> +	mux_handler := cors.New(opts).Handler(mux)
```suggestion
	muxHandler := cors.New(opts).Handler(mux)
```

v_1 is not idiomatic style lets use camel-casing.

2023-09-23 21:13 UTC, harshavardhana approved these changes

2023-09-29 12:28 UTC, ilyajob05 commented
@harshavardhana  hi! 
the workflow is still awaiting approval from the maintainer

2023-11-18 00:14 UTC, harshavardhana requested changes
let me think about this.

2023-11-18 00:14 UTC, harshavardhana commented on go.mod
> +	github.com/minio/pkg v1.7.5
Actually there is a problem we can't link this package here since `minio/pkg` is AGPLv3

2023-11-26 09:59 UTC, closed without merging

2023-11-26 10:03 UTC, harshavardhana commented
This is merged here https://github.com/harshavardhana/s3www/commit/b906d89ba84446133cdd097ff6294ff1f7f4a3a8